### ISSUE TITLE
Provider crashing

### ISSUE THREAD

**Issue by Patafix** [crossplane-contrib/provider-keycloak#189]
The provider is in version 1.8.0

The container is crashing after some tome and restart :

The last error is :
```
2024-11-29T15:47:06.567258246Z {"level":"info","ts":"2024-11-29T15:47:06Z","logger":"provider-keycloak","msg":"Async update callback failed","trackerUID":"fde67c29-37d6-485f-945d-80ce1a90ce71","resourceName":"XXXXXi","gvk":"client.keycloak.crossplane.io/v1alpha1, Kind=ProtocolMapper","error":"cannot get resource /, Kind=/ after an async update: ProtocolMapper.client.keycloak.crossplane.io \"\" not found"}
2024-11-29T15:47:09.187762985Z panic: assignment to entry in nil map
2024-11-29T15:47:09.187795746Z 
2024-11-29T15:47:09.187799729Z goroutine 181562 [running]:
2024-11-29T15:47:09.187803949Z reflect.mapassign0(0x1f7f3e0, 0xc00481ce20?, 0xc003efcf30?, 0xc003efcf30)
2024-11-29T15:47:09.187806815Z  runtime/map.go:1370 +0x1d
2024-11-29T15:47:09.187809852Z reflect.mapassign(0xc004254240?, 0xc004295c30?, 0x8b8209?, 0xc004254240?)
2024-11-29T15:47:09.187812519Z  reflect/value.go:3877 +0x8d
2024-11-29T15:47:09.187815958Z github.com/modern-go/reflect2.(*UnsafeMapType).UnsafeSetIndex(...)
2024-11-29T15:47:09.187819942Z  github.com/modern-go/reflect2@v1.0.2/unsafe_map.go:76
2024-11-29T15:47:09.187840607Z github.com/json-iterator/go.(*mapDecoder).Decode(0xc004df1220, 0xc002797dd0, 0xc004254240)
2024-11-29T15:47:09.187843675Z  github.com/json-iterator/go@v1.1.12/reflect_map.go:191 +0x325
2024-11-29T15:47:09.187847499Z github.com/json-iterator/go.(*structFieldDecoder).Decode(0xc00481cfe0, 0xc004295d28?, 0xc004254240)
2024-11-29T15:47:09.187850777Z  github.com/json-iterator/go@v1.1.12/reflect_struct_decoder.go:1054 +0x50
2024-11-29T15:47:09.187853441Z github.com/json-iterator/go.(*eightFieldsStructDecoder).Decode(0xc0015fafc0, 0xc002797dc0, 0xc004254240)
2024-11-29T15:47:09.187860761Z  github.com/json-iterator/go@v1.1.12/reflect_struct_decoder.go:897 +0x146
2024-11-29T15:47:09.187863782Z github.com/json-iterator/go.(*Iterator).ReadVal(0xc004254240, {0x1fba220, 0xc002797dc0})
2024-11-29T15:47:09.187867062Z  github.com/json-iterator/go@v1.1.12/reflect.go:79 +0x14b
2024-11-29T15:47:09.187871072Z github.com/json-iterator/go.(*frozenConfig).Unmarshal(0xc00036e280, {0xc000e64160?, 0xc0049d2f00?, 0xc0049d2e10?}, {0x1fba220, 0xc002797dc0})
2024-11-29T15:47:09.187877035Z  github.com/json-iterator/go@v1.1.12/config.go:348 +0x99
2024-11-29T15:47:09.187885507Z github.com/crossplane-contrib/provider-keycloak/apis/client/v1alpha1.(*ProtocolMapper).SetObservation(0xc002797b88, 0x225ad80?)
2024-11-29T15:47:09.187888563Z  github.com/crossplane-contrib/provider-keycloak/apis/client/v1alpha1/zz_protocolmapper_terraformed.go:43 +0x7e
2024-11-29T15:47:09.187915931Z github.com/crossplane/upjet/pkg/controller.(*terraformPluginSDKExternal).Update(0xc002dada40, {0x26b7db0, 0xc0032c2c40}, {0x26da4c0, 0xc002797b88})
2024-11-29T15:47:09.187931549Z  github.com/crossplane/upjet@v1.4.0/pkg/controller/external_tfpluginsdk.go:699 +0x2c2
2024-11-29T15:47:09.187945829Z github.com/crossplane/upjet/pkg/controller.(*terraformPluginSDKAsyncExternal).Update.func1()
2024-11-29T15:47:09.187947801Z  github.com/crossplane/upjet@v1.4.0/pkg/controller/external_async_tfpluginsdk.go:173 +0x145
2024-11-29T15:47:09.187949917Z created by github.com/crossplane/upjet/pkg/controller.(*terraformPluginSDKAsyncExternal).Update in goroutine 5380
2024-11-29T15:47:09.187954141Z  github.com/crossplane/upjet@v1.4.0/pkg/controller/external_async_tfpluginsdk.go:169 +0x14c
```

**Comment by Patafix** [comment]
After further investigation using debug mode, I discovered the issue was caused by the ProtocolMapper being reconciled infinitely.

The root cause is that if you don't specify all the fields in the config section, these fields are detected as differences, triggering constant reconciliation.

Additionally, there appears to be a minor memory leak during this process, eventually leading to an OOMKill of the container.

By updating my ProtocolMapper configuration as follows:

```

  "introspection.token.claim": "true",
  "userinfo.token.claim": "false"
```

the crash no longer occurs.

**Comment by Breee** [comment]
I'll look into that, we might be able to mitigate that

**Comment by denniskniep** [comment]
Same for [oidc_identity_provider](https://registry.terraform.io/providers/keycloak/keycloak/latest/docs/resources/oidc_identity_provider) `extra_config`

**Comment by greyarch** [comment]
Same for [the SAML Identity Provider](https://marketplace.upbound.io/providers/crossplane-contrib/provider-keycloak/v2.1.0/resources/saml.keycloak.crossplane.io/IdentityProvider/v1alpha1)

**Comment by greyarch** [comment]
Some more information. It seems that the problem is with boolean attributes in `extraConfig`.  `extraConfig` values have to be strings and that leads to mismatch during target discovery.
Hope this helps.
Btw, this is a very serious problem for me.

**Comment by Breee** [comment]
Can you show me your SAML Identity Provider?

**Comment by Breee** [comment]
The issue is pretty old, test if it happens nowadays in v2.20.0
